---
abstract: 'Plugin interface to Lingua::JA::Fold'
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-JA-Fold
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Lingua::JA::Fold: 0
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hideo55/p5-Template-Plugin-JA-Fold.git
version: 0.01
